runners:
  - name: aws-gpu-runner
    cloud: aws
    instance_type: g4dn.xlarge
    machine_image: ami-067a4ba2816407ee9
    region: eu-north-1
    preemptible:
      - true
      - false
    workflow: .github/workflows/test-gpu.yml
    labels:
      - cirun-aws-gpu
