runners:
  - name: aws-gpu-runner
    cloud: aws
    instance_type: g4dn.xlarge
    machine_image: ami-0139a05e194cbd9a0
    preemptible: false
    workflow: .github/workflows/test-gpu.yml
    labels:
      - cirun-aws-gpu
