runners:
  - name: aws-gpu-runner
    cloud: aws
    instance_type: g4dn.xlarge
    machine_image: ami-0756bd122da9b2618
    region: eu-west-1
    preemptible:
      - true
      - false
    labels:
      - cirun-aws-gpu
