runners:
  - name: aws-gpu-runner
    cloud: aws
    instance_type: g4dn.xlarge
    machine_image: ami-0678adbdcb4c3a662
    preemptible: false
    workflow: .github/workflows/build_gpu.yml
    labels:
      - aws-gpu
