runners:
  - name: aws-gpu-runner
    cloud: aws
    instance_type: g4dn.xlarge
    machine_image: ami-0285bfb786db80af3
    region: eu-west-1
    preemptible:
      - true
      - false
    labels:
      - cirun-aws-gpu
