# Based on pydata/xarray
codecov:
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        # Require 80% coverage
        target: 80
    changes: false

comment:
  layout: "diff, flags, files"
  behavior: once
  require_base: false
