fail_fast: false
default_stages:
  - pre-commit
  - pre-push
minimum_pre_commit_version: 2.16.0
repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.5.10
    hooks:
      - id: biome-format
        exclude: ^\.cruft\.json$ # inconsistent indentation with cruft - file never to be modified manually.
        groups: [format]
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
        groups: [format]
        exclude: ^pyproject[.]toml$
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.28.1
    hooks:
      - id: pyproject-fmt
        groups: [format]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.4
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        groups: [format]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: hatch check types
        language: system
        types: [python]
        files: ^(src|tests)/
        require_serial: true
        pass_filenames: false
        groups: [typing]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: detect-private-key
      - id: check-ast
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        groups: [format]
      - id: mixed-line-ending
        groups: [format]
        args: [--fix=lf]
      - id: trailing-whitespace
        groups: [format]
      - id: check-case-conflict
      # Check that there are no merge conflicts (could be generated by template sync)
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: no-commit-to-branch
        args: [--branch=main]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.29.0
    hooks:
      - id: zizmor
        args: [--no-progress, --fix]
