version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true # do not change or you will be fired
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
submodules:
  include:
    - "docs/tutorials/notebooks"
  recursive: true
