name: Bug report
description: anndata doesn’t do what it should? Please help us fix it!
#title: ...
type: Bug
labels:
  - Triage 🩺
#assignees: []
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Please make sure these conditions are met
      # description: ...
      options:
        - label: I have checked that this issue has not already been reported.
          required: true
        - label: I have confirmed this bug exists on the latest version of anndata.
          required: true
        - label: (optional) I have confirmed this bug exists on the main branch of anndata.
          required: false
  - type: markdown
    attributes:
      value: |
        **Note**: Please read [this guide][] detailing how to provide the necessary information for us to reproduce your bug.

        [this guide]: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports
  - type: textarea
    id: Report
    attributes:
      label: Report
      description: |
        Describe the bug you encountered, and what you were trying to do.
        Executable example must list dependencies in [inline script metadata][].
        When put in a file named `issue.py` using [uv run][] i.e., `uv run issue.py`, should show the issue.

        Please use [github markdown][] features for readability.

        [uv run]: https://docs.astral.sh/uv/guides/scripts/#running-a-script-with-dependencies
        [inline script metadata]: https://packaging.python.org/en/latest/specifications/inline-script-metadata/#example
        [github markdown]: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
      value: |
        Code:

        ```python
        # /// script
        # requires-python = ">=3.12"
        # dependencies = [
        #   "anndata@git+https://github.com/scverse/anndata.git",
        # ]
        # ///

        import anndata
        # your reproducer code
        ```

        Traceback:

        ```pytb

        ```
    validations:
      required: true
  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: |
        Which version of anndata and other related software you used.

        Please install `session-info2`, run the following command in a notebook,
        click the “Copy as Markdown” button,
        then paste the results into the text box below.

        ```pycon
        In[1]: import anndata, session_info2; session_info2.session_info(dependencies=True)
        ```

        Alternatively, run this in your virtual environment:

        ```python
        python -m session_info2 -f markdown
        ```
      render: markdown
    validations:
      required: true
