name: "Label stale issues"
on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 60
          days-before-pr-stale: -1 # We don't want to mark PRs as stale
          days-before-close: -1 # We don't want to close issues in this action
          stale-issue-label: stale
          exempt-issue-labels: pinned,enhancement
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity.
            Please add a comment if you want to keep the issue open. Thank you for your contributions!
          debug-only: true # enable dry-run, remove when we know from the logs it's working.
