name: Benchmark

on:
  push:
    branches: [main, "[0-9]+.[0-9]+.x"]
  pull_request:
    branches: [main]

env:
  FORCE_COLOR: "1"

defaults:
  run:
    # Add `-l` to GitHub’s default bash options to activate mamba environments
    # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#exit-codes-and-error-action-preference
    # https://github.com/mamba-org/setup-micromamba/#readme
    shell: bash -elo pipefail {0}

jobs:
  benchmark:
    permissions: {}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python: ["3.12"]
        os: [ubuntu-latest]

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}
      ASV_DIR: "./benchmarks"

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
          # no blob filter so asv can checkout other commits

      - run: git fetch origin main:main
        if: ${{ github.ref_name != 'main' }}
        # Errors on main branch

      - uses: mamba-org/setup-micromamba@add3a49764cedee8ee24e82dfde87f5bc2914462 # v2.0.7
        with:
          environment-name: asv
          cache-environment: true
          # Deps documented in https://asv.readthedocs.io/en/latest/installing.html
          # https://github.com/airspeed-velocity/asv/issues/1577
          create-args: >-
            python=${{ matrix.python }}
            asv>=0.6.4
            py_rattler<0.22
            conda-build

      - name: Cache datasets
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ~/.cache
          key: benchmark-state-${{ hashFiles('benchmarks/**') }}

      - name: Quick benchmark run
        working-directory: ${{ env.ASV_DIR }}
        run: |
          asv machine --yes
          asv run --dry-run --quick --show-stderr --verbose HEAD^!
