name: Pull Request Validation

on:
  pull_request:
    branches:
      - main
      - master
    types:
      # milestone changes
      - milestoned
      - demilestoned
      # label changes for “no milestone”
      - labeled
      - unlabeled
      # initial check
      - opened
      - edited
      - reopened
      # code change (e.g. this workflow)
      - synchronize

env:
  LABELS: ${{ join(github.event.pull_request.labels.*.name, '|') }}

jobs:
  check-milestone:
    name: "Triage: Check Milestone"
    runs-on: ubuntu-latest
    steps:
      - name: Check if merging isn’t blocked
        if: contains(env.LABELS, 'DON’T MERGE')
        run: exit 1
      - name: Check if a milestone is necessary and exists
        if: github.event.pull_request.milestone == null && contains(env.LABELS, 'no milestone') == false
        run: exit 1
